name: Ejecutar Script Bash

on:
  push:
    branches:
      - main
      - master

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      
      - name: Dar permisos de ejecución al script
        run: chmod +x src/hola.sh
      
      - name: Ejecutar el script
        run: ./src/hola.sh
EOF